# Generated by Django 4.2.14 on 2024-07-23 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO_CLASSIFIEDS', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='mileage',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
