# Generated by Django 4.2.14 on 2024-07-23 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO_CLASSIFIEDS', '0003_alter_listing_ad_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='ad_status',
            field=models.CharField(choices=[('sold', 'Sold'), ('pending', 'Pending'), ('for sale', 'For Sale')], default='For Sale', max_length=20),
        ),
    ]
