# Generated by Django 4.2.14 on 2024-07-24 07:07

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TURO_CLASSIFIEDS', '0005_intrestrequest'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='IntrestRequest',
            new_name='InterestRequest',
        ),
    ]
