# Generated by Django 4.2.14 on 2024-07-16 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AUTH', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
