# Generated by Django 4.2.14 on 2024-07-17 09:17

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('TURO', '0002_alter_vehicle_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='insurance_document',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_docs/'),
        ),
        migrations.AddField(
            model_name='vehicle',
            name='registration_document',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_docs/'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)]),
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aadhar_image', models.ImageField(blank=True, null=True, upload_to='aadhar/')),
                ('dl_image', models.ImageField(blank=True, null=True, upload_to='dl/')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
