# Generated by Django 4.2.14 on 2024-07-17 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0004_userprofile_address_userprofile_city_vehicle_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reservation',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=50),
        ),
    ]
