# Generated by Django 4.2.14 on 2024-07-17 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0005_alter_reservation_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='vehicleImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_image', models.ImageField(upload_to='vehicle-images/')),
            ],
        ),
    ]
