# Generated by Django 4.2.14 on 2024-07-17 12:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0006_vehicleimages'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vehicleimages',
            name='vehicle_image',
        ),
        migrations.AddField(
            model_name='vehicleimages',
            name='image',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='TURO.vehicle'),
        ),
    ]
