# Generated by Django 4.2.14 on 2024-07-17 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0007_remove_vehicleimages_vehicle_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicleimages',
            old_name='image',
            new_name='vehicle',
        ),
        migrations.AddField(
            model_name='vehicleimages',
            name='vehicle_image',
            field=models.ImageField(blank=True, null=True, upload_to='vehicle_image/'),
        ),
    ]
