# Generated by Django 4.2.14 on 2024-07-19 08:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0008_rename_image_vehicleimages_vehicle_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicle',
            name='engine_capacity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(10000)]),
        ),
    ]
