# Generated by Django 4.2.14 on 2024-07-19 09:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0009_vehicle_engine_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='vehicleimages',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to='thumbnails/'),
        ),
    ]
