# Generated by Django 4.2.14 on 2024-07-23 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0011_vehicle_transmission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='price_per_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
    ]
