# Generated by Django 4.2.14 on 2024-07-24 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0013_alter_vehicle_price_per_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='contact_number',
            field=models.IntegerField(default=0, max_length=10),
        ),
    ]
