# Generated by Django 4.2.14 on 2024-07-24 11:46

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0014_userprofile_contact_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='contact_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(code='invalid_contact_number', message='Contact number must be exactly 10 digits.', regex='^\\d{10}$')]),
        ),
    ]
