# Generated by Django 4.2.14 on 2024-07-26 05:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TURO', '0016_userprofile_profile_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reservation',
            name='vehicle',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='address',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='city',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='location',
        ),
        migrations.RemoveField(
            model_name='vehicle',
            name='price_per_day',
        ),
        migrations.CreateModel(
            name='RentListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('listing_date', models.DateField(auto_now_add=True)),
                ('price_per_day', models.DecimalField(decimal_places=2, max_digits=10)),
                ('availability', models.BooleanField(default=True)),
                ('city', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=200)),
                ('vehicle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rent_listings', to='TURO.vehicle')),
            ],
        ),
        migrations.AddField(
            model_name='reservation',
            name='rent_listing',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='reservations', to='TURO.rentlisting'),
            preserve_default=False,
        ),
    ]
